#!/usr/bin/env bash

# Find the workspace where nautilus is located
ws=$(hyprctl clients -j | jq -r '.[] | select(.class=="org.gnome.Nautilus") | .workspace.id' | sort -n | tail -n 1)

if [ -n "$ws" ]; then
    # If found, switch to it
    hyprctl dispatch workspace "$ws"
fi
