#!/usr/bin/env bash

# Find the workspace where kitty/alacritty is located
ws=$(hyprctl clients -j | jq -r '.[] | select(.class | test("^(Alacritty|kitty)$")) | .workspace.id' | sort -n | tail -n 1)

if [ -n "$ws" ]; then
    # If found, switch to it
    hyprctl dispatch workspace "$ws"
fi
