#!/usr/bin/env bash
find /usr/share/antergos/wallpapers \
     /usr/share/backgrounds \
     /usr/share/wallpapers \
     /usr/share/Wallpapers \
     "$HOME/.local/share/backgrounds" \
     "$HOME/.local/share/wallpapers" \
     "$HOME/Pictures/Wallpapers" \
     -type f \( -iname '*.*g' \) \
     2>/dev/null | nl > ~/.cache/wallpapers-list
zenity --info --text "Keep in mind that the shown wallpaper numberings are 1 higher than that used by the wallpaper script."
vim $HOME/.cache/wallpapers-list +$($HOME/GitHub/mine/config/hyprland-configs/no-wallpapers | cut -d '/' -f 1)
