#!/usr/bin/env bash
root=$(find /usr/share/{backgrounds,[wW]allpapers} -name "*.*g" -type f | wc -l) ; 
userpi=$(find $HOME/Pictures/Wallpapers -name "*.*g" -type f | wc -l);
userls=$(find $HOME/.local/share/{backgrounds,wallpapers} -name "*.*g" -type f | wc -l);
user=$(($userpi+$userls))
no=$(($root+$user))
#curr=$(cat $HOME/.cache/swaybg-wallstate)
# Define the two possible files
f1="$HOME/.cache/swaybg-wallstate"
f2="$HOME/.cache/swaybg-wallstate-random"

# Find the most recently modified of the two
latest=$(ls -t "$f1" "$f2" 2>/dev/null | head -n1)
width="${#no}"
# If one exists, read its contents into curr
if [ -n "$latest" ]; then
    curr=$(<"$latest")
else
    curr=""
fi
padded=$(printf "%0${width}d" "$curr")
echo "$padded/$no"
