#!/usr/bin/env bash
env __GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDORS_OVERRIDE=nvidia prime-run /home/fusion809/.local/share/bolt-launcher/rs3linux
