#!/usr/bin/env bash
if ! `ps ax | grep 1343400 &> /dev/null`; then
	steam steam://rungameid/1343400
else

	# Find the workspace where kitty is located
	ws=$(hyprctl clients -j | jq -r '.[] | select(.class=="steam_app_1343400") | .workspace.id' | tail -n 1)

	if [ -n "$ws" ]; then
    		# If found, switch to it
    		hyprctl dispatch workspace "$ws"
	fi 
fi
