#!/usr/bin/env bash
if `which turbo &> /dev/null`; then
	list=$(turbo -Py || sudo pacman -Syup | grep -v "core \|extra \|multilib \|testing \|multilib-testing \|extra-testing \|No.*packages\|AUR\|Synchronizing " | grep -vi "pacman" | grep -v "Update:" | grep -v "^$" | grep -v "json")
	no=$(echo $list | grep -v '^[[:space:]]*$' | wc -l)
fi
if [[ $no -gt 0 ]]; then
	echo "󰚰"
fi
